// ═══════════════════════════════════════════════════════════════════
//  PLUDUNI — Données · Espèces réelles de Lettonie / Vidzeme
// ═══════════════════════════════════════════════════════════════════

export const RARITY = {
  commun:      { l:'Commun',      p:5,   c:'#8B9B6E' },
  peu_commun:  { l:'Peu commun',  p:15,  c:'#C08A3E' },
  rare:        { l:'Rare',        p:40,  c:'#B5602F' },
  tres_rare:   { l:'Très rare',   p:100, c:'#8B3A2E' },
}

export const SIZE_MULT = { xs:1, s:1.5, m:2, l:2.5, xl:3 }

export const METHODS = {
  eye:   { l:'Vue directe',     mult:3,   c:'#4A5D32', on:'#EDE7D8' },
  scope: { l:'Longue-vue',      mult:2.5, c:'#6B7F4E', on:'#EDE7D8' },
  night: { l:'Vision nocturne', mult:2,   c:'#93A576', on:'#2B2620' },
  cam:   { l:'Caméra piège',    mult:1,   c:'#C3CDAE', on:'#3B4429' },
}

export const PLAYERS = [
  { id:'G', name:'Gaël' },
  { id:'P', name:'Pierre' },
  { id:'E', name:'Elena' },
  { id:'F', name:'Ferdinand' },
]

export const CATS = [
  { id:'mammiferes', e:'🦁', n:'Mammifères', lat:'Mammalia', subs:[
      { id:'Cervidés', lat:'Cervidae' }, { id:'Canidés', lat:'Canidae' },
      { id:'Félidés', lat:'Felidae' }, { id:'Mustélidés', lat:'Mustelidae' },
      { id:'Rongeurs', lat:'Rodentia / Lagomorpha' }, { id:'Autres', lat:'Erinaceidae / Suidae' },
  ]},
  { id:'oiseaux', e:'🦅', n:'Oiseaux', lat:'Aves', subs:[
      { id:'Gruidés', lat:'Gruidae' }, { id:'Strigidés', lat:'Strigidae' },
      { id:'Picidés', lat:'Picidae' }, { id:'Accipitridés', lat:'Accipitridae' },
      { id:'Ciconiidés', lat:'Ciconiidae' }, { id:'Corvidés', lat:'Corvidae' },
      { id:'Tétraonidés', lat:'Tetraonidae' },
  ]},
  { id:'arbres', e:'🌳', n:'Arbres', lat:'Arbores', subs:[
      { id:'Fagacées', lat:'Fagaceae' }, { id:'Bétulacées', lat:'Betulaceae' },
      { id:'Pinacées', lat:'Pinaceae' }, { id:'Salicacées', lat:'Salicaceae' },
      { id:'Rosacées', lat:'Rosaceae' }, { id:'Sapindacées', lat:'Sapindaceae' },
      { id:'Malvacées', lat:'Malvaceae' },
  ]},
  { id:'champignons', e:'🍄', n:'Champignons', lat:'Fungi', subs:[
      { id:'Bolétales', lat:'Boletales' }, { id:'Agaricales', lat:'Agaricales' },
      { id:'Russulales', lat:'Russulales' }, { id:'Cantharellales', lat:'Cantharellales' },
  ]},
  { id:'lichens', e:'🍃', n:'Lichens & mousses', lat:'Lichenes / Bryophyta', subs:[
      { id:'Lichens', lat:'Lichenes' }, { id:'Mousses', lat:'Bryophyta' },
  ]},
  { id:'insectes', e:'🦋', n:'Insectes', lat:'Insecta', subs:[
      { id:'Lépidoptères', lat:'Lepidoptera' }, { id:'Coléoptères', lat:'Coleoptera' },
      { id:'Odonates', lat:'Odonata' }, { id:'Hyménoptères', lat:'Hymenoptera' },
  ]},
]

export const SPECIES = [
  { id:'elan', n:'Élan', lat:'Alces alces', e:'🫎', cat:'mammiferes', sub:'Cervidés', r:'rare', sz:'xl',
    obs:{ Ferdinand:['cam'] }, bonus:{},
    inds:[{n:'Gustav',note:'Femelle ou jeune mâle, sans bois',d:'12/06/2026',b:[],
       gps:[57.3115,25.2712], by:'Ferdinand', method:'cam', weather:'Nuit claire, 14 °C', time:'23h20',
       story:"Il surgit de nulle part à 23h20, immense, et reste quatre minutes devant l'objectif à brouter les jeunes pousses. L'échelle est saisissante : sa tête dépasse la branche basse du bouleau.",
       desc:'Absence de bois — femelle adulte ou jeune mâle de 2 ans. Robe brun foncé, garrot très marqué.'}],
    anecdote:"L'élan est le plus grand cervidé du monde : un mâle adulte peut atteindre 800 kg. Il nage remarquablement bien et peut plonger jusqu'à 5 m pour atteindre des plantes aquatiques. Ses longues pattes lui permettent de traverser 1 m de neige sans effort.",
    saisons:{printemps:'Mise bas en mai-juin. Les femelles deviennent très défensives.',ete:'Fréquente les zones humides pour se nourrir et échapper aux insectes.',automne:'Rut en septembre-octobre. Les mâles deviennent imprévisibles.',hiver:'Se rabat sur les jeunes pousses de saule et bouleau. Perd ses bois.'},
    alim:'Saule, bouleau, plantes aquatiques. 20–30 kg/jour.',
    hab:'Zones humides, lisières. Territoire 10–30 km². Solitaire.',
    dng:'Femelle avec veau dangereuse. Mâle imprévisible en rut (sept–oct).' },
  { id:'cerf', n:'Cerf élaphe', lat:'Cervus elaphus', e:'🦌', cat:'mammiferes', sub:'Cervidés', r:'peu_commun', sz:'l',
    obs:{ Ferdinand:['cam'], Pierre:['eye'] }, bonus:{},
    inds:[{n:'Biche 1',note:"Femelle adulte, pelage roux d'été",d:'Juin 2026',b:[],
       gps:[57.3142,25.2769], by:'Pierre', method:'eye', weather:'Aube brumeuse, 8 °C', time:'05h50',
       story:"Rencontre à l'aube en lisière est. Elle m'a repéré avant que je la voie — figée, oreilles pivotantes. On s'est observés une trentaine de secondes avant qu'elle décide que ça suffisait.",
       desc:'Femelle adulte, pelage roux vif estival, pas de tache de gestation visible.'}],
    anecdote:"Le brame du cerf porte à plus de 5 km par nuit calme. Les bois repoussent chaque année à raison de 2 cm par jour — c'est le tissu à croissance la plus rapide du règne animal.",
    saisons:{printemps:'Chute des bois puis repousse sous velours. Naissance des faons en mai-juin.',ete:'Pelage roux vif. Vie en hardes séparées mâles/femelles.',automne:'Le brame. Les mâles rassemblent leurs harems et combattent.',hiver:'Pelage gris épais. Regroupements pour économiser l\'énergie.'},
    alim:'Herbes, baies, glands, champignons, écorce.',
    hab:'Forêt et lisières. Sociable en hardes.', dng:'Aucun danger hors rut.' },
  { id:'chevreuil', n:'Chevreuil', lat:'Capreolus capreolus', e:'🦌', cat:'mammiferes', sub:'Cervidés', r:'commun', sz:'s',
    obs:{ Ferdinand:['cam','eye'], Pierre:['eye'], Noan:['cam'] }, bonus:{},
    inds:[
      {n:'Velours',note:'Mâle, bois en velours',d:'Juin 2026',b:['jeune_bois'],
       gps:[57.3122,25.2733], by:'Ferdinand', method:'cam', weather:'Journée douce, 17 °C', time:'19h12',
       story:"À trois mètres de la caméra, il broute sans se douter de rien. Les bois encore en velours, tout duveteux. Il est resté sept minutes.",
       desc:'Brocard adulte, bois en velours de 18-20 cm, trois pointes par merrain.'},
      {n:'Chevrette 1',note:'Probable allaitante',d:'Juin 2026',b:['bebe'],
       gps:[57.3119,25.2728], by:'Pierre', method:'eye', weather:'Soir dégagé, 15 °C', time:'20h40',
       story:"Croisée dans la clairière sud. Mamelles visibles — un faon devait être couché tout près. Je n'ai pas insisté.",
       desc:'Chevrette adulte, mamelles développées indiquant une lactation en cours.'}],
    anecdote:"Le chevreuil est le seul ongulé à pratiquer la diapause embryonnaire : fécondé en juillet, l'embryon ne s'implante qu'en décembre. L'aboiement qu'on entend en forêt, c'est lui — un cri d'alarme sec qui prévient tout le voisinage.",
    saisons:{printemps:'Naissance des faons en mai. Bois débarrassés du velours.',ete:'Rut en juillet-août. Poursuites en cercles caractéristiques.',automne:'Pelage gris-brun. Constitution des réserves.',hiver:'Regroupement en petites hardes. Chute des bois en octobre-novembre.'},
    alim:'Pousses, baies, champignons, lierre. Sélectif.',
    hab:'Lisières et clairières. Territoire 30–60 ha.', dng:'Aucun.' },
  { id:'sanglier', n:'Sanglier', lat:'Sus scrofa', e:'🐗', cat:'mammiferes', sub:'Autres', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Racines, glands, vers, larves, charognes. Omnivore.',
    hab:'Forêt dense, souilles près de l\'eau. En compagnies.',
    dng:'Laie avec marcassins agressive. Peut charger.' },
  { id:'renard', n:'Renard roux', lat:'Vulpes vulpes', e:'🦊', cat:'mammiferes', sub:'Canidés', r:'commun', sz:'s',
    obs:{ Ferdinand:['cam','eye'], Pierre:['cam'], Vera:['eye'] }, bonus:{ Ferdinand:['terrier','bebe'] },
    inds:[
      {n:'Roux 1',note:'Adulte sain, actif le matin',d:'Avril 2026',b:[],
       gps:[57.3135,25.2755], by:'Ferdinand', method:'eye', weather:'Matin frais, 6 °C', time:'07h15',
       story:"Le classique : il trottine le long de la lisière, s'arrête, écoute, plonge le museau dans l'herbe. Un mulot de moins.",
       desc:'Adulte en bon état, pelage dense et brillant, queue fournie à extrémité blanche.'},
      {n:'Galeux',note:'⚠️ Gale sarcoptique avancée',d:'Juin 2026',b:[],
       gps:[57.3138,25.2761], by:'Ferdinand', method:'cam', weather:'Couvert, 13 °C', time:'11h05',
       story:"Difficile à regarder. Les flancs dégarnis, le poil terne, la démarche lente. Sans traitement, il ne passera pas l'automne. J'ai contacté un centre de soins.",
       desc:'Adulte atteint de gale sarcoptique : zones dégarnies importantes sur flancs et dos, croûtes visibles.'},
      {n:'Renardeau A',note:'Jeune de l\'année',d:'Juin 2026',b:['bebe'],
       gps:[57.3140,25.2758], by:'Ferdinand', method:'cam', weather:'Fin de journée, 16 °C', time:'18h30',
       story:"Deux renardeaux qui se poursuivent devant la caméra, complètement insouciants. Le terrier ne doit pas être loin.",
       desc:'Jeune de l\'année, environ 3 mois, pelage encore laineux.'},
      {n:'Renardeau B',note:'Jeune de l\'année',d:'Juin 2026',b:['bebe'],
       gps:[57.3140,25.2758], by:'Ferdinand', method:'cam', weather:'Fin de journée, 16 °C', time:'18h30',
       story:"Le frère ou la sœur du premier. Un peu plus petit, un peu plus prudent.",
       desc:'Jeune de l\'année, légèrement plus petit que son congénère.'}],
    anecdote:"Le renard utilise le champ magnétique terrestre pour chasser : il oriente son bond nord-est et réussit 73 % de ses attaques dans cet axe, contre 18 % dans les autres directions. Il possède plus de 20 vocalisations différentes.",
    saisons:{printemps:'Naissance des renardeaux en avril. Les adultes chassent en permanence.',ete:'Émancipation progressive des jeunes. Régime riche en fruits et insectes.',automne:'Dispersion des jeunes. Constitution des réserves de graisse.',hiver:'Rut en janvier-février. Cris nocturnes caractéristiques.'},
    alim:'Rongeurs, lapins, oeufs, fruits, insectes.',
    hab:'Lisières, bocage. Terrier actif sur la propriété.',
    dng:'⚠️ Un individu porteur de gale — contagieux pour le chien.' },
  { id:'loup', n:'Loup gris', lat:'Canis lupus', e:'🐺', cat:'mammiferes', sub:'Canidés', r:'tres_rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Cerf, chevreuil, sanglier, castor. Chasse en meute.',
    hab:'Grands massifs forestiers. Territoire 100–300 km².',
    dng:'Très craintif envers l\'humain. Surveille les chiens.' },
  { id:'viverrin', n:'Chien viverrin', lat:'Nyctereutes procyonoides', e:'🦝', cat:'mammiferes', sub:'Canidés', r:'peu_commun', sz:'s',
    obs:{ Ferdinand:['cam','night'] }, bonus:{},
    inds:[{n:'Viverrin 1',note:'Nocturne, invasif',d:'Multiple',b:[]}],
    alim:'Grenouilles, poissons, baies, rongeurs, charognes.',
    hab:'Zones humides. Espèce invasive. Torpeur hivernale.',
    dng:'⚠️ Vecteur de rage. Danger pour la basse-cour.' },
  { id:'lynx', n:'Lynx boréal', lat:'Lynx lynx', e:'🐆', cat:'mammiferes', sub:'Félidés', r:'tres_rare', sz:'m',
    obs:{ Ferdinand:['cam'] }, bonus:{ Ferdinand:['terrier'] },
    inds:[
      {n:'Loki',note:'Adulte mâle, roux tacheté',d:'07/06/2026',b:['adulte'],
       gps:[57.3128,25.2741], by:'Ferdinand', method:'cam', weather:'Ciel dégagé, 10 °C', time:'08h38',
       story:"Première capture du lynx sur la propriété. Il traverse le corridor nord d'un pas tranquille, sans un regard pour la caméra. Un moment suspendu — on a mis trois jours à y croire.",
       desc:'Adulte en pleine santé, pelage roux vif densément tacheté, pinceaux auriculaires bien marqués. Estimation : 4-6 ans.'},
      {n:'Inconnu',note:'Second individu, à identifier',d:'07/06/2026',b:[],
       gps:[57.3131,25.2748], by:'Ferdinand', method:'cam', weather:'Ciel dégagé, 10 °C', time:'08h39',
       story:"Une seconde silhouette passe une minute après Loki. Trop floue pour trancher — peut-être une femelle suivie, peut-être le même animal revenu sur ses pas.",
       desc:'Non identifiable formellement. Taille comparable au premier individu.'}],
    anecdote:"Le lynx ne rugit pas : il miaule, ronronne et pousse des cris rauques. En Lettonie, la population est passée de moins de 100 individus dans les années 1950 à environ 1 200 aujourd'hui. Il peut bondir sur 7 mètres d'un seul élan.",
    saisons:{printemps:'Mise bas en mai. La femelle reste cantonnée près de la tanière.',ete:'Élevage des jeunes. Chasse plus fréquente pour nourrir la portée.',automne:'Les jeunes accompagnent la mère. Territoire parcouru intensément.',hiver:'Rut en février-mars. Traces bien visibles dans la neige.'},
    alim:'Chevreuil (70–80%), cerf, lièvre. Affût et bond.',
    hab:'Forêt dense. Territoire 200–500 km². Solitaire.',
    dng:'Aucun pour l\'humain. Très craintif.' },
  { id:'chat_sauvage', n:'Chat sauvage', lat:'Felis silvestris', e:'🐈', cat:'mammiferes', sub:'Félidés', r:'rare', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Rongeurs, oiseaux, lapereaux.',
    hab:'Forêt de feuillus, lisières broussailleuses. Discret.', dng:'Aucun. Fuit l\'humain.' },
  { id:'blaireau', n:'Blaireau européen', lat:'Meles meles', e:'🦡', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'m',
    obs:{ Ferdinand:['cam'], Noan:['cam'] }, bonus:{},
    inds:[{n:'Blaireau 1',note:'Nocturne, blairaudière probable',d:'Hiver 2025',b:[]}],
    alim:'Vers de terre (80%), baies, insectes, rongeurs.',
    hab:'Blairaudière multigénérationnelle. Torpeur hivernale.', dng:'Inoffensif.' },
  { id:'martre', n:'Martre des pins', lat:'Martes martes', e:'🦦', cat:'mammiferes', sub:'Mustélidés', r:'rare', sz:'xs',
    obs:{ Ferdinand:['cam'] }, bonus:{},
    inds:[{n:'Martre 1',note:'Silhouette longiligne nocturne',d:'Nuit',b:[]}],
    alim:'Rongeurs, oiseaux, oeufs, baies, miel.',
    hab:'Forêt de conifères et mixte. Arboricole.', dng:'Aucun pour l\'humain.' },
  { id:'putois', n:'Putois d\'Europe', lat:'Mustela putorius', e:'🦨', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Amphibiens, rongeurs, oiseaux.',
    hab:'Zones humides, lisières, granges.', dng:'Aucun.' },
  { id:'hermine', n:'Hermine', lat:'Mustela erminea', e:'🐁', cat:'mammiferes', sub:'Mustélidés', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Campagnols, mulots, lapereaux.',
    hab:'Lisières, murets, prairies. Blanche en hiver.', dng:'Aucun.' },
  { id:'loutre', n:'Loutre d\'Europe', lat:'Lutra lutra', e:'🦦', cat:'mammiferes', sub:'Mustélidés', r:'rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, amphibiens, écrevisses.',
    hab:'Rivière Līčupe, berges des lacs. Marque avec épreintes.', dng:'Aucun.' },
  { id:'vison', n:'Vison d\'Europe', lat:'Mustela lutreola', e:'🦫', cat:'mammiferes', sub:'Mustélidés', r:'tres_rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Amphibiens, poissons, petits rongeurs.',
    hab:'Berges des cours d\'eau. Très menacé en Europe.', dng:'Aucun.' },
  { id:'castor', n:'Castor d\'Eurasie', lat:'Castor fiber', e:'🦫', cat:'mammiferes', sub:'Rongeurs', r:'peu_commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce, rameaux, plantes aquatiques.',
    hab:'Līčupe et lacs. Construit huttes et barrages.', dng:'Aucun.' },
  { id:'ecureuil', n:'Écureuil roux', lat:'Sciurus vulgaris', e:'🐿️', cat:'mammiferes', sub:'Rongeurs', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines de conifères, noisettes, glands, champignons.',
    hab:'Forêt de conifères et mixte. Arboricole diurne.', dng:'Aucun.' },
  { id:'lievre', n:'Lièvre d\'Europe', lat:'Lepus europaeus', e:'🐇', cat:'mammiferes', sub:'Rongeurs', r:'commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Herbes, écorces, cultures.',
    hab:'Champs, lisières, prairies. Gîte à découvert.', dng:'Aucun.' },
  { id:'herisson', n:'Hérisson', lat:'Erinaceus europaeus', e:'🦔', cat:'mammiferes', sub:'Autres', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Insectes, vers, limaces, oeufs.',
    hab:'Jardins, lisières, haies. Nocturne. Hiberne.', dng:'Aucun.' },

  { id:'grue', n:'Grue cendrée', lat:'Grus grus', e:'🪽', cat:'oiseaux', sub:'Gruidés', r:'rare', sz:'m',
    obs:{ Ferdinand:['cam'], Pierre:['eye'] }, bonus:{},
    inds:[{n:'Grue 1',note:'Calotte rouge, ~120cm',d:'Juin 2026',b:[]}],
    alim:'Grains, insectes, vers, amphibiens.',
    hab:'Zones humides. Migratrice. Parade nuptiale spectaculaire.', dng:'Aucun.' },
  { id:'hulotte', n:'Chouette hulotte', lat:'Strix aluco', e:'🦉', cat:'oiseaux', sub:'Strigidés', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Campagnols, mulots, oiseaux, amphibiens.',
    hab:'Forêt mixte, vieux arbres à cavités. Nocturne.', dng:'Aucun.' },
  { id:'pic_noir', n:'Pic noir', lat:'Dryocopus martius', e:'🐦‍⬛', cat:'oiseaux', sub:'Picidés', r:'peu_commun', sz:'s',
    obs:{}, bonus:{}, inds:[],
    alim:'Fourmis, larves xylophages sous l\'écorce.',
    hab:'Vieilles forêts de conifères. Plus grand pic d\'Europe.', dng:'Aucun.' },
  { id:'pygargue', n:'Pygargue à queue blanche', lat:'Haliaeetus albicilla', e:'🦅', cat:'oiseaux', sub:'Accipitridés', r:'rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, oiseaux d\'eau, charognes.',
    hab:'Grands lacs, envergure jusqu\'à 2,4m.', dng:'Aucun.' },
  { id:'cigogne_noire', n:'Cigogne noire', lat:'Ciconia nigra', e:'🐦', cat:'oiseaux', sub:'Ciconiidés', r:'rare', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Poissons, amphibiens, insectes aquatiques.',
    hab:'Forêts humides isolées. Très discrète, farouche.', dng:'Aucun.' },
  { id:'geai', n:'Geai des chênes', lat:'Garrulus glandarius', e:'🐦', cat:'oiseaux', sub:'Corvidés', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Glands, faines, insectes, oeufs.',
    hab:'Forêts de feuillus. Sentinelle bruyante de la forêt.', dng:'Aucun.' },
  { id:'grand_tetras', n:'Grand tétras', lat:'Tetrao urogallus', e:'🦃', cat:'oiseaux', sub:'Tétraonidés', r:'tres_rare', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Aiguilles de pin, baies, bourgeons.',
    hab:'Vieilles pinèdes. Parade au chant.', dng:'Mâle en parade peut charger.' },

  { id:'chene', n:'Chêne pédonculé', lat:'Quercus robur', e:'🌳', cat:'arbres', sub:'Fagacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Glands = nourriture clé pour sanglier, geai, écureuil.',
    hab:'Forêts de feuillus, sols riches. Peut vivre 500+ ans.', dng:'—' },
  { id:'hetre', n:'Hêtre commun', lat:'Fagus sylvatica', e:'🌳', cat:'arbres', sub:'Fagacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Faines consommées par de nombreux animaux.',
    hab:'Forêts denses, sols frais. Écorce lisse grise.', dng:'—' },
  { id:'bouleau', n:'Bouleau pubescent', lat:'Betula pubescens', e:'🌲', cat:'arbres', sub:'Bétulacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce et rameaux broutés par l\'élan.',
    hab:'Pionnier, zones humides. Écorce blanche typique.', dng:'—' },
  { id:'aulne', n:'Aulne glutineux', lat:'Alnus glutinosa', e:'🌲', cat:'arbres', sub:'Bétulacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines pour tarins et sizerins.',
    hab:'Berges de la Līčupe, sols gorgés d\'eau.', dng:'—' },
  { id:'epicea', n:'Épicéa commun', lat:'Picea abies', e:'🌲', cat:'arbres', sub:'Pinacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Graines de cônes pour écureuil, bec-croisé.',
    hab:'Dominant de la forêt boréale. Abri du lynx.', dng:'—' },
  { id:'pin', n:'Pin sylvestre', lat:'Pinus sylvestris', e:'🌲', cat:'arbres', sub:'Pinacées', r:'commun', sz:'xl',
    obs:{}, bonus:{}, inds:[],
    alim:'Aiguilles = nourriture du grand tétras.',
    hab:'Sols pauvres et sableux. Écorce orangée en haut.', dng:'—' },
  { id:'tremble', n:'Tremble', lat:'Populus tremula', e:'🌳', cat:'arbres', sub:'Salicacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Écorce très appréciée du castor et du lièvre.',
    hab:'Pionnier, lisières. Feuilles qui tremblent au vent.', dng:'—' },
  { id:'sorbier', n:'Sorbier des oiseleurs', lat:'Sorbus aucuparia', e:'🌳', cat:'arbres', sub:'Rosacées', r:'commun', sz:'m',
    obs:{}, bonus:{}, inds:[],
    alim:'Baies rouges pour grives, merles, renard.',
    hab:'Lisières, clairières. Baies orangées en automne.', dng:'—' },
  { id:'tilleul', n:'Tilleul à petites feuilles', lat:'Tilia cordata', e:'🌳', cat:'arbres', sub:'Malvacées', r:'peu_commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Fleurs mellifères pour abeilles et bourdons.',
    hab:'Forêts de feuillus, parcs. Arbre symbolique balte.', dng:'—' },
  { id:'erable', n:'Érable plane', lat:'Acer platanoides', e:'🍁', cat:'arbres', sub:'Sapindacées', r:'commun', sz:'l',
    obs:{}, bonus:{}, inds:[],
    alim:'Samares pour rongeurs et oiseaux.',
    hab:'Forêts mixtes. Feuillage jaune-rouge éclatant en automne.', dng:'—' },

  { id:'cepe', n:'Cèpe de Bordeaux', lat:'Boletus edulis', e:'🍄', cat:'champignons', sub:'Bolétales', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Symbiose mycorhizienne avec épicéas et pins.',
    hab:'Sous conifères et feuillus. Comestible réputé.', dng:'—' },
  { id:'bolet_orange', n:'Bolet orangé', lat:'Leccinum aurantiacum', e:'🍄', cat:'champignons', sub:'Bolétales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec trembles et bouleaux.',
    hab:'Sous trembles. Chapeau orange vif. Comestible.', dng:'—' },
  { id:'girolle', n:'Girolle', lat:'Cantharellus cibarius', e:'🍄', cat:'champignons', sub:'Cantharellales', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec de nombreux arbres.',
    hab:'Forêts moussues. Jaune d\'or, odeur d\'abricot. Comestible.', dng:'—' },
  { id:'amanite', n:'Amanite tue-mouches', lat:'Amanita muscaria', e:'🍄', cat:'champignons', sub:'Agaricales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhize avec bouleaux et épicéas.',
    hab:'Sous bouleaux. Rouge à points blancs.', dng:'⚠️ Toxique — ne pas consommer.' },
  { id:'russule', n:'Russule charbonnière', lat:'Russula cyanoxantha', e:'🍄', cat:'champignons', sub:'Russulales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Mycorhizienne.',
    hab:'Forêts de feuillus. Chapeau violacé-vert. Comestible.', dng:'—' },
  { id:'coprin', n:'Coprin chevelu', lat:'Coprinus comatus', e:'🍄', cat:'champignons', sub:'Agaricales', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Saprophyte (décompose la matière organique).',
    hab:'Prairies, bords de chemins. Se liquéfie en vieillissant.', dng:'—' },

  { id:'cladonie', n:'Cladonie des rennes', lat:'Cladonia rangiferina', e:'🍃', cat:'lichens', sub:'Lichens', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Nourriture hivernale des rennes (nord).',
    hab:'Sols pauvres, pinèdes sèches. Tapis gris clair.', dng:'—' },
  { id:'usnee', n:'Usnée barbue', lat:'Usnea barbata', e:'🍃', cat:'lichens', sub:'Lichens', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Pend des branches. Bio-indicateur d\'air pur.', dng:'—' },
  { id:'sphaigne', n:'Sphaigne', lat:'Sphagnum sp.', e:'🍃', cat:'lichens', sub:'Mousses', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Tourbières, zones humides. Forme la tourbe.', dng:'—' },
  { id:'polytric', n:'Polytric commun', lat:'Polytrichum commune', e:'🍃', cat:'lichens', sub:'Mousses', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'—',
    hab:'Sous-bois humides, tourbières. Grande mousse dressée.', dng:'—' },

  { id:'machaon', n:'Machaon', lat:'Papilio machaon', e:'🦋', cat:'insectes', sub:'Lépidoptères', r:'peu_commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Chenille sur ombellifères, adulte butineur.',
    hab:'Prairies fleuries, lisières. Grand papillon jaune-noir.', dng:'—' },
  { id:'petit_paon', n:'Paon-du-jour', lat:'Aglais io', e:'🦋', cat:'insectes', sub:'Lépidoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Chenille sur orties, adulte sur fleurs.',
    hab:'Jardins, lisières. Ocelles bleus en forme d\'yeux.', dng:'—' },
  { id:'lucane', n:'Lucane cerf-volant', lat:'Lucanus cervus', e:'🪲', cat:'insectes', sub:'Coléoptères', r:'rare', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Larve xylophage dans le bois mort de chêne.',
    hab:'Vieux chênes, bois mort. Plus grand coléoptère d\'Europe.', dng:'—' },
  { id:'carabe', n:'Carabe doré', lat:'Carabus auratus', e:'🪲', cat:'insectes', sub:'Coléoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Prédateur de limaces, vers, chenilles.',
    hab:'Sol des forêts et jardins. Reflets vert-doré.', dng:'—' },
  { id:'libellule', n:'Libellule déprimée', lat:'Libellula depressa', e:'🪰', cat:'insectes', sub:'Odonates', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Prédatrice de moucherons et moustiques.',
    hab:'Bords des lacs et mares. Abdomen large bleuté.', dng:'—' },
  { id:'bourdon', n:'Bourdon terrestre', lat:'Bombus terrestris', e:'🐝', cat:'insectes', sub:'Hyménoptères', r:'commun', sz:'xs',
    obs:{}, bonus:{}, inds:[],
    alim:'Nectar et pollen. Pollinisateur majeur.',
    hab:'Prairies, jardins. Niche au sol. Bande jaune.', dng:'Piqûre possible si menacé.' },
]

export const ACHIEVEMENTS = [
  { e:'🏆', n:'Grand prédateur',    d:'Observer le lynx',                w:'Ferdinand', on:true,  pts:150 },
  { e:'🌙', n:'Chasseur nocturne',  d:'3 espèces nocturnes en une nuit', w:'Ferdinand', on:true,  pts:80 },
  { e:'🦊', n:'Famille renard',     d:'Observer des renardeaux',         w:'Ferdinand', on:true,  pts:60 },
  { e:'🏠', n:'Détective terrier',  d:'Trouver un gîte ou terrier',      w:'Ferdinand', on:true,  pts:70 },
  { e:'👶', n:'Nurserie',           d:'Observer des jeunes de l\'année', w:'Ferdinand, Pierre', on:true, pts:50 },
  { e:'❄️', n:'Trace de loup',      d:'Première observation de loup',    w:'—', on:false, pts:200 },
  { e:'🐻', n:'Ours observé',       d:'Observer un ours brun',           w:'—', on:false, pts:300 },
  { e:'🦌', n:'Brame du cerf',      d:'Entendre le brame (sept–oct)',    w:'—', on:false, pts:60 },
  { e:'🦫', n:'Barrage castor',     d:'Trouver un barrage sur la Līčupe',w:'—', on:false, pts:90 },
  { e:'🌊', n:'Loutre aperçue',     d:'Observer une loutre',             w:'—', on:false, pts:180 },
  { e:'🍄', n:'Mycologue',          d:'10 champignons identifiés',       w:'—', on:false, pts:100 },
  { e:'🌳', n:'Dendrologue',        d:'Tous les arbres de la propriété', w:'—', on:false, pts:120 },
  { e:'🦋', n:'Entomologiste',      d:'6 insectes différents',           w:'—', on:false, pts:80 },
  { e:'🦅', n:'Ornithologue',       d:'Tous les oiseaux',                w:'—', on:false, pts:140 },
  { e:'🌅', n:'Lève-tôt',           d:'Une observation avant 6h du matin',w:'—', on:false, pts:40 },
  { e:'🥶', n:'Hivernal',           d:'Observer par moins de −15°C',     w:'—', on:false, pts:70 },
  { e:'👁️', n:'Œil de lynx',        d:'10 espèces vues à l\'œil nu',     w:'—', on:false, pts:110 },
  { e:'🌧️', n:'Sous la pluie',      d:'Une sortie complète sous la pluie',w:'—', on:false, pts:35 },
  { e:'🏞️', n:'Le grand chelem',    d:'Une espèce de chaque règne',      w:'—', on:false, pts:160 },
  { e:'📸', n:'Photographe',        d:'20 photos nettes validées',       w:'—', on:false, pts:90 },
  { e:'🥚', n:'Découvreur de nid',  d:'Trouver un nid occupé',           w:'—', on:false, pts:75 },
  { e:'🐾', n:'Pisteur',            d:'Identifier 5 empreintes au sol',  w:'—', on:false, pts:65 },
  { e:'🌒', n:'Pleine lune',        d:'Observer une nuit de pleine lune',w:'—', on:false, pts:45 },
  { e:'🔭', n:'Longue portée',      d:'Observation à plus de 300 m',     w:'—', on:false, pts:55 },
  { e:'🦡', n:'Le clan',            d:'Voir 3 blaireaux ensemble',       w:'—', on:false, pts:85 },
  { e:'🌿', n:'Complétiste',        d:'50 espèces observées',            w:'—', on:false, pts:250 },
]

// points de badges par joueur
export function badgePts(playerName) {
  return ACHIEVEMENTS.filter(a => a.on && a.w.includes(playerName))
    .reduce((s, a) => s + (a.pts || 0), 0)
}

export function calcPts(sp, playerName) {
  const methods = sp.obs[playerName] || []
  if (!methods.length) return 0
  const best = methods.reduce((b, m) => (METHODS[m]?.mult || 0) > (METHODS[b]?.mult || 0) ? m : b, methods[0])
  const bonuses = sp.bonus[playerName] || []
  return Math.round(
    RARITY[sp.r].p * SIZE_MULT[sp.sz] * (METHODS[best]?.mult || 1) +
    (bonuses.includes('bebe') ? 20 : 0) +
    (bonuses.includes('terrier') ? 30 : 0)
  )
}
export function speciesPts(playerName) {
  return SPECIES.reduce((sum, sp) => sum + calcPts(sp, playerName), 0)
}
export function totalPts(playerName) {
  return speciesPts(playerName) + badgePts(playerName)
}
export function isObserved(sp) {
  return Object.values(sp.obs).some(v => v && v.length)
}
